spring:
    profiles:
        active: prod
    config:
        name: yama

management:
    context-path: /api/actuator

truststore:
    file: ca.jks
    pass: password
keystore:
    file: server.p12
    pass: password